schema_version = "1.1.13"
id = "papl_tools"
version = "1.1.13"
name = "Papl Tools"
tagline = "Multipapl Toolkit"
maintainer = "Paplmulti"
type = "add-on"
blender_version_min = "4.2.0"
license = [ "SPDX:GPL-3.0-or-later",]
